### ISSUE TITLE
build fails on missing ims.apk

### ISSUE THREAD

**Issue by blitzn0r** [cryptomilk/android_device_sony_lilac#14]
My build fails with the following message:
```

99% 1454/1455] glob vendor/qcom/opensource/interfaces/wifi/supplicant/1.0/Android.bp
ninja: error: 'vendor/sony/lilac/proprietary/app/ims/ims.apk', needed by '/media/simon/Volume/lineage/repo/out/target/product/lilac/obj/APPS/ims_intermediates/package.apk', missing and no known rule to make it
19:08:01 ninja failed with: exit status 1

#### failed to build some targets (14:57 (mm:ss)) ####
```

Before that, there are many warnings ([see file](https://github.com/cryptomilk/android_device_sony_lilac/files/2793028/build-error.log))

Did something go wrong while extracting vendor blobs? I just bought the phone and it is already updated to 9.0.

I would love to be able to build. Maybe I can help with development...

**Comment by cryptomilk** [comment]
See current TESTING branches
