### ISSUE TITLE
twrp 9.0 build errer

### ISSUE THREAD

**Issue by iovf** [cryptomilk/android_device_sony_lilac#16]
build 8.1 no problem
build lineageos 9.0

export WITH_TWRP=true
export ALLOW_MISSING_DEPENDENCIES=true
source build/envsetup.sh
lunch lineage_lilac-eng
mka recoveryimage -j6

error: bootable/recovery-twrp/applypatch/Android.bp:15:1: module "applypatch_defaults" already defined
       bootable/recovery/applypatch/Android.bp:15:1 <-- previous definition here
error: bootable/recovery-twrp/otautil/Android.bp:15:1: module "libotautil" already defined

many error 
i delete bootable/recovery applypatch,otautil... folders

then...

system/core/init/result.h:150:12: error: call to deleted constructor of 'android::init::Error'
    return Error(errno);
           ^~~~~~~~~~~~
system/core/init/result.h:139:5: note: 'Error' has been explicitly marked deleted here
    Error(Error&&) = delete;
    ^
system/core/init/result.h:159:50: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
              typename = std::enable_if_t<!(std::is_same_v<std::decay_t<U>, Result<T>> &&

how to fix it...

**Comment by cryptomilk** [comment]
Use the minimal twrp build and the twrp-9.0 branches of all repos.
