### ISSUE TITLE
I'm now unable to download anything to my SD card, especially Nextcloud, Kindle, etc.

### ISSUE THREAD

**Issue by YamiYukiSenpai** [cryptomilk/android_device_sony_lilac#47]
* Nextcloud can't download any files
* VLC won't show any videos on the app
* Can't download books on Kindle
* This is potentially a separate problem, but installing from Play Store will soft-reboot the device.

**Comment by cryptomilk** [comment]
Then open bugs for each of those applications and tell them to use the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html)

An app correctly implementing this is [OpenCamera](https://sourceforge.net/p/opencamera/code/) (GPL), see their [FAQ](https://opencamera.sourceforge.io/help.html#faq) section. With that app storing data on the sdcard simply works.

In Android 10 the Storage Access Framework is a requirement now!

**Comment by cryptomilk** [comment]
See also https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage/

**Comment by YamiYukiSenpai** [comment]
I was referring to LineageOS 16 ROM that was in XDA

**Comment by cryptomilk** [comment]
It applies to Android 9 too. OpenCamera works ...

**Comment by YamiYukiSenpai** [comment]
It only stopped working when I switched to LineageOS.  I have other phones with Android 9 running on LineageOS, and they're fine

**Comment by cryptomilk** [comment]
Fixed with v1.2
