### ISSUE TITLE
Error building ROM

### ISSUE THREAD

**Issue by jacen05** [cryptomilk/android_device_sony_lilac#8]
Hello,

I tried to follow the how-to but failed at `repo sync` step. I run into the following error: `fatal: Couldn't find remote ref refs/heads/lineage-15.1`.
I attached the log file, errors are at lines 57309 and 73619. curl also had many HTTP 404 Not found, but I don't know if this is important.
In the end I got the message `error: Exited sync due to fetch errors`.
After that I don't have the device/sony/lilac/extract-files.sh, so I cannot continue the how-to. If I try again and again the repo sync command, it is much quickier (caching I guess), but I still get the same error.

What can I do to resolve this problem?
[repo_sync_output.log](https://github.com/cryptomilk/android_device_sony_lilac/files/2238635/repo_sync_output.log)

By the way I had to create manually the folder .repo/local_manifests before writing the file roomservice.xml

**Comment by cryptomilk** [comment]
Find the fetch error in the log and fix it. Syncing the lineage tree is not related to lilac at all

**Comment by jacen05** [comment]
Sorry to bother you again, but I can successfully `repo sync` without the roomservice.xml. Here is the log file : 
[repo_sync_lineage.log](https://github.com/cryptomilk/android_device_sony_lilac/files/2321600/repo_sync_lineage.log)

When adding the roomservice.xml, I looked at the fetch error, and it the same in the previous log ouptut than it is now:
[repo_sync_lilac.log](https://github.com/cryptomilk/android_device_sony_lilac/files/2321602/repo_sync_lilac.log)
`error: Cannot fetch cryptomilk/android_vendor_sony_lilac`

So I guess it is related to the android vendor repo. But I don't understand why it does not succeed, as the repo name seems correct. Any idea of root cause?

**Comment by cryptomilk** [comment]
github doesn't support the git protocol

**Comment by jacen05** [comment]
Replacing git by https in the `repo init` command did not change anything. 
I think my error may be linked to the default values in the .repo/manifest.xml file. Some of my default values for Github are:
`<remote  name="github" fetch=".." review="review.lineageos.org" />`
`<default revision="refs/heads/lineage-15.1" remote="github" sync-c="true" sync-j="4" />`
I tried to sync replacing the github remote fetch by https://github.com in files .repo/manifest.xml, and .repo/manifests/default.xml, but same error.

Would you mind sharing your own default values?

**Comment by culots** [comment]
You shouldn't have to change anything in the default manifest.xml file. That file will be changed from time-to-time by LineageOS peoples, so you really don't want to edit that. Anyway, the local_manifest option prevents the need to edit the default manifest. With the local manifest provided you should be able to sync with no issues.

Those 404 errors in your log can be ignored, they are related to the clone-bundle lack. You can pass the argument '--no-clone-bundle' to repo, ie: 'repo sync --no-clone-bundle' to weed those errors out. Or you can safely ignore them.

To better isolate the problem pass '-j 1' & '--trace' to repo, ie: 'repo --trace sync -j1' so the output it puts out is cleaner and more informative.

**Comment by jacen05** [comment]
Thanks for the info. First I tried to change the "github" remote in local_manifest, but as it was already defined in another manifest I wasn't authorized to redefine it. That's why I played with the other manifest files. I understand that it wasn't a good idea, the problem probably lies elsewhere.

So I tried again, this time with the options provided: `repo --trace sync -j1 --no-clone-bundle &> ../repo_sync.log`
I also tried on another Linux box, result is the same.
Here is the full log:
[repo_sync.log](https://github.com/cryptomilk/android_device_sony_lilac/files/2324871/repo_sync.log)

And here is the part that I think is relevant:
```
: export GIT_DIR=/path/to/repo/.repo/projects/vendor/sony/lilac.git
: git fetch github --tags +refs/heads/lineage-15.1:refs/remotes/github/lineage-15.1 1>| 2>|
fatal: Couldn't find remote ref refs/heads/lineage-15.1
: git fetch github --tags +refs/heads/lineage-15.1:refs/remotes/github/lineage-15.1 1>| 2>|
fatal: Couldn't find remote ref refs/heads/lineage-15.1
: git pack-refs --all --prune 1>| 2>|
error: Cannot fetch cryptomilk/android_vendor_sony_lilac

error: Exited sync due to fetch errors
```
However I'm not very knowledgeable about git/repo, does the error mean that repo tried to fetch the (non-existent) lineage-15.1 branch for repository cryptomilk/android_vendor_sony_lilac? Or branch lineage-15.1 for another repository? Or anything else called lineageos-15.1?

If I look at the files containing the error string, I get these results:
```
$ grep -ri 'refs/heads/lineage-15.1' ./.repo
./.repo/manifests.git/.repo_config.json:    "refs/heads/lineage-15.1"
./.repo/manifests.git/config:	merge = refs/heads/lineage-15.1
./.repo/manifests/default.xml:  <default revision="refs/heads/lineage-15.1"
```
Should I change one of these values?
